/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.przemo.tradexclient.gui;

import com.jidesoft.dialog.JideOptionPane;
import com.przemo.tradexclient.remote.RemoteAction;
import com.przemo.tradexclient.remote.RemoteActionInitializationException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;


/**
 *
 * @author Przemo
 */
public class RemoveOrderForm extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form RemoveOrderForm
     */
    public RemoveOrderForm()  {
        initComponents();
        jButton1.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove Order");

        jLabel1.setText("Order ID:");

        jButton1.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtOrderId;
    // End of variables declaration//GEN-END:variables

@Override
public void setVisible(boolean vis){
    super.setVisible(vis);
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    this.setLocation((int)(dim.getWidth()-this.getWidth())/2, (int)((dim.getHeight()-this.getHeight())/2));
}
    
    @Override
    public void actionPerformed(ActionEvent e) {
        try{
        long tid = Long.parseLong(txtOrderId.getText());
        if(e.getSource().equals(jButton1)){ //the OK button clicked
            if(JideOptionPane.showConfirmDialog(this, "Are you sure you want to remove order "+txtOrderId.getText()+"?", "Remove Order", JideOptionPane.YES_NO_OPTION) == JideOptionPane.YES_OPTION){
                try {
                    //Remove the order - call the remote action object
                    if(!RemoteAction.removeOrder(tid)){
                        JideOptionPane.showMessageDialog(this, "Order could not be removed!");             
                    } else {
                        this.setVisible(false);
                    }
                } catch (RemoteActionInitializationException | RemoteException | NotBoundException ex) {
                    java.util.logging.Logger.getLogger(RemoveOrderForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }    
        }catch(NumberFormatException ex){         
            java.util.logging.Logger.getLogger(RemoveOrderForm.class.getName()).log(Level.WARNING,null, ex);
        }
        
    }

    
}
